### ISSUE TITLE
test-fgemm fails sometime

### ISSUE THREAD

**Issue by gmh33** [linbox-team/fflas-ffpack#10]
Lubuntu LTS x64, gcc 4.8, gmp 5.1.3, lapack 3.5.0, lbas 1.2.20110419

**Comment by ClementPernet** [comment]
Fixed in e5fcbf25bd131fd92f10d8e98130d7e3cc31421d.
It was a bug in the multiprecision fgemm with RNS (computation of the InfNorm did not support submatrices and transposes).
