### ISSUE TITLE
Optimize ftrtri

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#100]
- write an iterative base case
- write a testsuite
- fix/improve the benchmark
- setup an autotuning system to find the threshold

**Comment by ledentp** [comment]
- [x] write an iterative base case
- [x] write a testsuite
- [ ]  fix/improve the benchmark
- [ ] setup an autotuning system to find the threshold
By seeking the threshold manually, it seems that it's close to 32.

**Comment by ClementPernet** [comment]
Done in #109
