### ISSUE TITLE
had to disable simd to get it to compile

### ISSUE THREAD

**Issue by DanGrayson** [linbox-team/fflas-ffpack#103]
Under Mac OS X 10.12.4 with clang as the compiler and with -O2 as the optimization level I had trouble : various built in AVX instructions are given the "xsave" attribute by the compiler, and then it is an error to include them and inline them in a function that is not given that attribute, also.

Let me know if this is not a known problem or is not easily reproducible and I can give a more precise bug report.

**Comment by ClementPernet** [comment]
Hi, thanks for the report.
This is a bug that has not been encountered so far. We have one OS-X 10.9.5 machine on our continuous integration farm and the issue was never raised.
Can you please post your config.log and any information you may find relevant, so we could investigate the issue?
Thanks.

**Comment by ClementPernet** [comment]
By the way:
 - are you compiling the latest stable version v2.2.2, or the latest master branch of the git repo ?
 - which givaro are you linking to ? latest release v4.0.2 or master branch ?
The SIMD detection is done in Givaro, so could you also please include the config.log of your Givaro build?

**Comment by P1K** [comment]
Cannot reproduce on recent OS-X builds, and simd detection has changed since 2017
