### ISSUE TITLE
cblas detection incorrect

### ISSUE THREAD

**Issue by DanGrayson** [linbox-team/fflas-ffpack#105]
An examination of `fflas-ffpack-blas.m4` shows that HAVE_CBLAS is defined if and only if BLAS is detected (and thus HAVE_BLAS is defined), but actually, one needs to test for CBLAS separately.  As a consequence, on a system with BLAS and without CBLAS, such as Scientific Linux 7.3 with `lapack-devel` and `blas-devel` installed, linking will fail with undefined CBLAS functions, such as `cblas_dcopy`.

Then if I work around that by patching the macro so HAVE_CBLAS is not defined, and include the resulting file `config-blas.h` into two files, I get duplicate definition errors in the linker for various CBLAS functions, such as `cblas_dcopy`.  The workaround for that is to add `static` as a storage class for all those definitions.  That's fine if the function is to be inlined, anyway.

(This is for use in Macaulay2.)

**Comment by DanGrayson** [comment]
Here are the changes I made:

https://github.com/Macaulay2/fflas-ffpack/commit/c3e5fc9b2aa5b3be87722bfceda42f4a95b9defa

**Comment by ClementPernet** [comment]
Hi, thanks for the report. This is now fixed upstream since PR #147 has been merged, and will be in release 2.3.1.
