### ISSUE TITLE
benchmark-pluq segfault benchmark-ftrsm always runs in sequential

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#11]
These two pbs seem to be related and boil down to the use of variadic macros in the Paladin FORBLOCK1D command.

The trick to have a macro function overriden with multiple number of arguments requires two instances of __VA_ARGS__ which in turn makes the precompiler produce two lines
`` #pragma omp task``
in a row.
Removing this variadic macros fixes both problems.
Paladin interface should therefore be fixed accordingly: FORBLOCK1D should only accept 4 arguments: 
(iter, size, Helper, instructions).

**Comment by sultanz** [comment]
Resolved
