### ISSUE TITLE
Can't disable sse4 instructions

### ISSUE THREAD

**Issue by antonio-rojas** [linbox-team/fflas-ffpack#145]
The configure flags --disable-sse4.1 --disable-sse4.2avx (documented in ./configure --help) don't have any effect: sse4.x instructions are still enabled. The flags to disable other instruction sets work fine, only these two seem to be broken.

**Comment by ClementPernet** [comment]
Thanks for the report. This is indeed a bug with the period in the configure option name. This is fixed upstream. I may release a minor version update with this fix of the 3 libraries: givaro, linbox and fflas-ffpack.
