### ISSUE TITLE
Sporadic test-fgemm-check failures (2.3.0)

### ISSUE THREAD

**Issue by jamesjer** [linbox-team/fflas-ffpack#146]
I'm working on updating Fedora packages to the latest givaro, fflas-ffpack, and linbox releases.  When the fflas-ffpack test suite runs, sometimes test-fgemm-check fails.  Here is an example on x86_64:

Checking ........................Modular<double> mod 346639 ... FAILED
FAILED with seed = 1511323555521716

**Comment by ClementPernet** [comment]
This is a known bug : see #139 where we acknowledge that it not only happens on OSX but also fedora.
It seems to only happen with the checker (a verification tool), and not the main computational routine fgemm and is quite hard to track (it seems to be system specific).
Hence we decided to release 2.3.0 and 2.3.1 with this bug unresolved. But we will work on fixing it for hte next coming release.

**Comment by ClementPernet** [comment]
Fixed in d8cd67d
