### ISSUE TITLE
fflas_fgemv.inl:139:11: error: no matching function for call to 'fgemv'

### ISSUE THREAD

**Issue by jgdumas** [linbox-team/fflas-ffpack#15]
home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:139:11: error: no matching function for call to 'fgemv'
return fgemv (F, ta, M, N, alpha,
^~~~~
../linbox/blackbox/apply.h:128:12: note: in instantiation of function template specialization 'FFLAS::fgemv<Givaro::ZRing<Givaro::Integer> >' requested here
FFLAS::fgemv(_domain, FFLAS::FflasTrans,
^
../linbox/algorithms/rational-solver.inl:1012:9: note: in instantiation of member function 'LinBox::BlasApply<Givaro::ZRing<Givaro::Integer> >::applyVTrans' requested here
BAR.applyVTrans(certnumer_A, A_check, cert.numer);
^
../linbox/solutions/solve.h:557:21: note: in instantiation of function template specialization 'LinBox::RationalSolver<Givaro::ZRing<Givaro::Integer>, Givaro::Modular<double, double>, LinBox::RandomPrimeIterator, LinBox::DixonTraits>::monolithicSolve<LinBox::BlasMatrix<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > > >' requested here
status= rsolve.monolithicSolve(x, d, A, b, false, false, (int)m.maxTries(),
^
../linbox/solutions/solve.h:509:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, Givaro::ZRing<Givaro::Integer> >' requested here
return solve(x, d, A, b, tag, mDixon);
^
../linbox/solutions/solve.h:497:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, Givaro::ZRing<Givaro::Integer> >' requested here
return solve(x, d, B, b, tag, m);
^
../linbox/solutions/solve.h:484:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>, LinBox::SparseMatrixFormat::SparseSeq> >' requested here
return solve(x, d, A, b, typename FieldTraits<typename BB::Field>::categoryTag(), m);
^
solve.C:233:17: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>, LinBox::SparseMatrixFormat::SparseSeq>, LinBox::BlasEliminationTraits>' requested here
solve (X, d, A, B, Method::BlasElimination());
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:360:2: note: candidate function not viable: no known conversion from 'Givaro::Integer *' to 'const int64_t *' (aka 'const long *') for 6th argument
fgemv (const Givaro::ZRing<int64_t>& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:398:2: note: candidate function not viable: no known conversion from 'Givaro::Integer *' to 'const Givaro::DoubleDomain::ConstElement_ptr' (aka 'const double *const') for 6th argument
fgemv (const Givaro::DoubleDomain& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:432:2: note: candidate function not viable: no known conversion from 'Givaro::Integer *' to 'const Givaro::FloatDomain::ConstElement_ptr' (aka 'const float *const') for 6th argument
fgemv (const Givaro::FloatDomain& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv_mp.inl:40:2: note: candidate function not viable: no known conversion from 'const typename ZRing<Integer>::Element' (aka 'const Givaro::Integer') to 'const FFPACK::rns_double::Element' (aka 'const FFPACK::rns_double_elt') for 5th argument
fgemv (const FFPACK::RNSInteger<FFPACK::rns_double>& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv_mp.inl:66:2: note: candidate function not viable: no known conversion from 'const Givaro::ZRing<Givaro::Integer>' to 'const FFPACK::RNSIntegerMod<FFPACK::rns_double>' for 1st argument
fgemv (const FFPACK::RNSIntegerMod<FFPACK::rns_double>& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:92:2: note: candidate template ignored: could not match 'ConvertTo<FFLAS::ElementCategories::MachineFloatTag>' against 'ConvertTo<FFLAS::ElementCategories::RNSElementTag>'
fgemv (const Field& F,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:147:2: note: candidate template ignored: could not match 'FFLAS::ModeCategories::DelayedTag' against 'FFLAS::ModeCategories::ConvertTo<FFLAS::ElementCategories::RNSElementTag>'
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:216:2: note: candidate template ignored: could not match 'FFLAS::ModeCategories::DefaultTag' against 'FFLAS::ModeCategories::ConvertTo<FFLAS::ElementCategories::RNSElementTag>'
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:250:2: note: candidate template ignored: could not match 'FFLAS::ModeCategories::LazyTag' against 'FFLAS::ModeCategories::ConvertTo<FFLAS::ElementCategories::RNSElementTag>'
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:417:2: note: candidate template ignored: could not match 'FFLAS::ModeCategories::DefaultBoundedTag' against 'FFLAS::ModeCategories::ConvertTo<FFLAS::ElementCategories::RNSElementTag>'
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:123:2: note: candidate function template not viable: requires 12 arguments, but 13 were provided
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
In file included from solve.C:37:
In file included from ../linbox/matrix/sparse-matrix.h:70:
In file included from ../linbox/matrix/sparsematrix/sparse-generic.h:80:
In file included from ../linbox/matrix/matrix-domain.h:68:
In file included from ../linbox/matrix/matrixdomain/blas-matrix-domain.h:968:
../linbox/matrix/matrixdomain/blas-matrix-domain.inl:1219:17: warning: implicit conversion changes signedness: 'int' to 'size_t' (aka 'unsigned long') [-Wsign-conversion]
1, 0,(int) B.getOrder(), A.getPointer(), 1, B.getPointer() );
^~~~~~~~~~~~~~~~~~
../linbox/matrix/matrixdomain/blas-matrix-domain.h:508:11: note: in instantiation of member function 'LinBox::BlasMatrixDomainMulin<Givaro::ZRing<Givaro::Integer>, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::BlasPermutation<unsigned long> >::operator()' requested here
return BlasMatrixDomainMulin<Field,Operand2,Operand1>()(field(),A,B);
^
../linbox/algorithms/rational-solver.inl:1152:9: note: in instantiation of function template specialization 'LinBox::BlasMatrixDomain<Givaro::ZRing<Givaro::Integer> >::mulin_right<LinBox::BlasPermutation<unsigned long>, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > > >' requested here
BMDI.mulin_right(TAS_P, newb);
^
../linbox/solutions/solve.h:557:21: note: in instantiation of function template specialization 'LinBox::RationalSolver<Givaro::ZRing<Givaro::Integer>, Givaro::Modular<double, double>, LinBox::RandomPrimeIterator, LinBox::DixonTraits>::monolithicSolve<LinBox::BlasMatrix<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > > >' requested here
status= rsolve.monolithicSolve(x, d, A, b, false, false, (int)m.maxTries(),
^
../linbox/solutions/solve.h:509:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, Givaro::ZRing<Givaro::Integer> >' requested here
return solve(x, d, A, b, tag, mDixon);
^
../linbox/solutions/solve.h:497:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, Givaro::ZRing<Givaro::Integer> >' requested here
return solve(x, d, B, b, tag, m);
^
../linbox/solutions/solve.h:484:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>, LinBox::SparseMatrixFormat::SparseSeq> >' requested here
return solve(x, d, A, b, typename FieldTraits<typename BB::Field>::categoryTag(), m);
^
solve.C:233:17: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>, LinBox::SparseMatrixFormat::SparseSeq>, LinBox::BlasEliminationTraits>' requested here
solve (X, d, A, B, Method::BlasElimination());
^
In file included from solve.C:38:
In file included from ../linbox/solutions/solve.h:41:
In file included from ../linbox/algorithms/rational-solver.h:1045:
In file included from ../linbox/algorithms/rational-solver.inl:37:
In file included from ../linbox/algorithms/lifting-container.h:39:
../linbox/blackbox/apply.h:107:5: error: no matching function for call to 'fgemv'
FFLAS::fgemv(_domain, FFLAS::FflasNoTrans,
^~~~~~~~~~~~
../linbox/algorithms/rational-solver.inl:1191:9: note: in instantiation of member function 'LinBox::BlasApply<Givaro::ZRing<Givaro::Integer> >::applyV' requested here
BAR.applyV(newNumer, *P, answer_to_vf.numer);
^
../linbox/solutions/solve.h:557:21: note: in instantiation of function template specialization 'LinBox::RationalSolver<Givaro::ZRing<Givaro::Integer>, Givaro::Modular<double, double>, LinBox::RandomPrimeIterator, LinBox::DixonTraits>::monolithicSolve<LinBox::BlasMatrix<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > > >' requested here
status= rsolve.monolithicSolve(x, d, A, b, false, false, (int)m.maxTries(),
^
../linbox/solutions/solve.h:509:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, Givaro::ZRing<Givaro::Integer> >' requested here
return solve(x, d, A, b, tag, mDixon);
^
../linbox/solutions/solve.h:497:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, Givaro::ZRing<Givaro::Integer> >' requested here
return solve(x, d, B, b, tag, m);
^
../linbox/solutions/solve.h:484:10: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>, LinBox::SparseMatrixFormat::SparseSeq> >' requested here
return solve(x, d, A, b, typename FieldTraits<typename BB::Field>::categoryTag(), m);
^
solve.C:233:17: note: in instantiation of function template specialization 'LinBox::solve<LinBox::BlasVector<Givaro::ZRing<Givaro::Integer>, std::vector<Givaro::Integer, std::allocator<Givaro::Integer> > >, LinBox::SparseMatrix<Givaro::ZRing<Givaro::Integer>, LinBox::SparseMatrixFormat::SparseSeq>, LinBox::BlasEliminationTraits>' requested here
solve (X, d, A, B, Method::BlasElimination());
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:123:2: note: candidate template ignored: substitution failure [with Field = Givaro::ZRing<Givaro::Integer>]
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:92:2: note: candidate function template not viable: requires 13 arguments, but 12 were provided
fgemv (const Field& F,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:147:2: note: candidate function template not viable: requires 13 arguments, but 12 were provided
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:216:2: note: candidate function template not viable: requires 13 arguments, but 12 were provided
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:250:2: note: candidate function template not viable: requires 13 arguments, but 12 were provided
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:417:2: note: candidate function template not viable: requires 13 arguments, but 12 were provided
fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:360:2: note: candidate function not viable: requires 13 arguments, but 12 were provided
fgemv (const Givaro::ZRing<int64_t>& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:398:2: note: candidate function not viable: requires 13 arguments, but 12 were provided
fgemv (const Givaro::DoubleDomain& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv.inl:432:2: note: candidate function not viable: requires 13 arguments, but 12 were provided
fgemv (const Givaro::FloatDomain& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv_mp.inl:40:2: note: candidate function not viable: requires 13 arguments, but 12 were provided
fgemv (const FFPACK::RNSInteger<FFPACK::rns_double>& F, const FFLAS_TRANSPOSE ta,
^
/home/breusta/jenkins/makers/../local/clang++/include/fflas-ffpack/fflas/fflas_fgemv_mp.inl:66:2: note: candidate function not viable: requires 13 arguments, but 12 were provided
fgemv (const FFPACK::RNSIntegerMod<FFPACK::rns_double>& F, const FFLAS_TRANSPOSE ta,
^
278 warnings and 2 errors generated.
Makefile:673: recipe for target 'solve.o' failed
make[1]: *** [solve.o] Error 1
make[1]: Leaving directory '/home/breusta/jenkins/workspace/LinBox-clang++/label/private-linalg-alize-x86_64-debian-8.0/onlineNodes/private-linalg-alize-x86_64-debian-8.0/examples'

**Comment by jgdumas** [comment]
/home/breusta/soft/fflas-ffpack-1.4.0/include/fflas-ffpack/fflas/fflas_fgemv.inl:142:28: error: no matching function for call to ‘fgemv(const Givaro::ZRing<Givaro::Integer>&, const FFLAS::FFLAS_TRANSPOSE&, const size_t&, const size_t&, const Element&, Givaro::Integer*, const size_t&, Givaro::Integer*, const size_t&, const Element&, Givaro::ZRing<Givaro::Integer>::Element*&, const size_t&, FFLAS::MMHelper<Givaro::ZRing<Givaro::Integer>, FFLAS::MMHelperAlgo::Classic, FFLAS::ModeCategories::ConvertTo<FFLAS::ElementCategories::RNSElementTag>, FFLAS::ParSeqHelper::Sequential>&)’
           beta, Y, incY, HW);
                            ^
/home/breusta/soft/fflas-ffpack-1.4.0/include/fflas-ffpack/fflas/fflas_fgemv.inl:142:28: note: candidates are:
/home/breusta/soft/fflas-ffpack-1.4.0/include/fflas-ffpack/fflas/fflas_fgemv.inl:123:2: note: template<class Field> typename Field::Element_ptr FFLAS::fgemv(const Field&, FFLAS::FFLAS_TRANSPOSE, size_t, size_t, typename Field::Element, typename Field::ConstElement_ptr, size_t, typename Field::ConstElement_ptr, size_t, typename Field::Element, typename Field::Element_ptr, size_t)
  fgemv (const Field& F, const FFLAS_TRANSPOSE ta,
  ^
/home/breusta/soft/fflas-ffpack-1.4.0/include/fflas-ffpack/fflas/fflas_fgemv.inl:123:2: note:   template argument deduction/substitution failed:
/home/breusta/soft/fflas-ffpack-1.4.0/include/fflas-ffpack/fflas/fflas_fgemv.inl:142:28: note:   candidate expects 12 arguments, 13 provided
           beta, Y, incY, HW);
                            ^

**Comment by ClementPernet** [comment]
Hi,

This seems to be related to the change you did in 53451c6f3d058ab2d80d3a902c412e9b5f6c6b44
I see you just reverted it or something similar in 5839879e153a4a43fdb3dbe0568ed25dababf010
Does it solve the pb or do you still want me to look at it?

Can you give me some info on how to reproduce it? Which linbox file compilation are you running? Does it only occur with clang++ and not g++ ?
