### ISSUE TITLE
test-fgemm and test-fgemv failing on *some* big endian archs

### ISSUE THREAD

**Issue by d-torrance** [linbox-team/fflas-ffpack#155]
There were some new build failures from the recently uploaded version 2.3.2 Debian package.

In particular, [mips](https://buildd.debian.org/status/fetch.php?pkg=fflas-ffpack&arch=mips&ver=2.3.2-1~exp1&stamp=1515634998&raw=0), [hppa](https://buildd.debian.org/status/fetch.php?pkg=fflas-ffpack&arch=hppa&ver=2.3.2-1~exp1&stamp=1515637152&raw=0), and [powerpc](https://buildd.debian.org/status/fetch.php?pkg=fflas-ffpack&arch=powerpc&ver=2.3.2-1~exp1&stamp=1515632995&raw=0).

Note that some other big endian archs built just fine, e.g., ppc64 and s390x.

Here is a snippet from the mips build log:

    FAIL: test-fgemm
    ================

    Checking ..........................Modular<double> mod 3739 ... PASSED 
    Checking ........................Modular<double> mod 880603 ... PASSED 
    Checking ........................Modular<double> mod 174299 ... PASSED 
    Checking ..................ModularBalanced<double> mod 3739 ... PASSED 
    Checking ................ModularBalanced<double> mod 880603 ... PASSED 
    Checking ................ModularBalanced<double> mod 174299 ... PASSED 
    Checking .............................Modular<float> mod 41 ... PASSED 
    Checking ............................Modular<float> mod 467 ... PASSED 
    Checking ............................Modular<float> mod 227 ... PASSED 
    Checking .....................ModularBalanced<float> mod 41 ... PASSED 
    Checking ....................ModularBalanced<float> mod 983 ... PASSED 
    Checking ....................ModularBalanced<float> mod 479 ... PASSED 
    Checking .............Modular<int32_t, uint32_t> modulo 167 ... PASSED 
    Checking ............Modular<int32_t, uint32_t> modulo 4057 ... PASSED 
    Checking ............Modular<int32_t, uint32_t> modulo 1249 ... PASSED 
    Checking ..................ModularBalanced<int32_t> mod 167 ... PASSED 
    Checking .................ModularBalanced<int32_t> mod 8147 ... PASSED 
    Checking .................ModularBalanced<int32_t> mod 1249 ... PASSED 
    Checking ............Modular<int64_t, int64_t> modulo 30367 ... PASSED 
    Checking .........Modular<int64_t, int64_t> modulo 12939217 ... PASSED 
    Checking ..........Modular<int64_t, int64_t> modulo 1485023 ... PASSED 
    Checking ................ModularBalanced<int64_t> mod 30367 ... PASSED 
    Checking .............ModularBalanced<int64_t> mod 29716441 ... PASSED 
    Checking ..............ModularBalanced<int64_t> mod 3582179 ... PASSED 
    Checking .....Modular<[IntType]> modulo 4661054187089311381 ... PASSED 
    Checking .....Modular<[IntType]> modulo 6783506999268437929 ... PASSED 
    Checking .....Modular<[IntType]> modulo 8262053159415228583 ... PASSED 
    Checking Modular<[IntType]> modulo 125362684583636023061407857899543082653 ... PASSED 
    Checking Modular<[IntType]> modulo 86822601181474265213599135872204500929 ... PASSED 
    Checking Modular<[IntType]> modulo 168680734304741979462085465925888682199 ... PASSED 
    Checking Modular<RecInt::ruint<7>, RecInt::ruint<8>> modulo 125362684583636023061407857899543082653 ... FAIL
    a   :1, b   : 0
    m   :5, n   : 7, k   : 23
    ldA :27, ldB : 30, ldC : 18
    Error C[0,0]=69041236273432517510307103148611703030 D[0,0]=65082715771525157715977298404163739873
    Error C[0,1]=115656123716822262970231947331626609387 D[0,1]=68978818819987087691747594666896454723
    Error C[0,2]=61729777712648137197071475025702283479 D[0,2]=81363438112060914392559495975940611054
    Error C[0,3]=110427501070004294081413529997027272225 D[0,3]=35829529517568166554252182604470964804
    Error C[0,4]=83636919353552188986034797762395300140 D[0,4]=22449098847496036240831387313973175377
    Error C[0,5]=77090715357403831806247098472029014610 D[0,5]=44970795326172314186731250255575821496
    Error C[0,6]=91254074447096166613041133182927634527 D[0,6]=102211012632600819222948899609125323554
    Error C[1,0]=124922334293203682574230028918196201653 D[1,0]=32551655291443742225973030166223944151
    Error C[1,1]=8642687490546573017122844080111629231 D[1,1]=48445771976011885784567593974591406863
    Error C[1,2]=43961233500680412373644414033861706369 D[1,2]=117173634309196254107590105926943578946
    Error C[1,3]=104403889863365889162489341640472434413 D[1,3]=86189653707744575569645144616643297046
    Error C[1,4]=69048890193242972773812066415638857788 D[1,4]=41983017599429437182389511677388420184
    Error C[1,5]=1925638160639087928409422823105532045 D[1,5]=66109593894395032834721386718477734989
    Error C[1,6]=86120681432319451465167455439722470622 D[1,6]=5712416626168925795252163245161965251
    Error C[2,0]=103147909891345814221261198738597359820 D[2,0]=110515308773099207974657588277703711728
    Error C[2,1]=25733339300273691774840016263749467872 D[2,1]=98410417253831188409161354206825728484
    Error C[2,2]=88017328756114053163918706658752926980 D[2,2]=101219621671213374149665353414159754747
    Error C[2,3]=79473338687662918182172910302076629929 D[2,3]=85404293754342096793697653984684428582
    Error C[2,4]=86891383582536581352075235221077980621 D[2,4]=80676365575800095955584746434415592638
    Error C[2,5]=2713026029712445757275701860695395411 D[2,5]=82556476982917423257647981567932494584
    XXXXXXX
    XXXXXXX
    XXXXXXX
    XXXXXXX
    XXXXXXX
    FAILED 
    FAIL test-fgemm (exit status: 1)

    FAIL: test-fgemv
    ================

    Checking ........................Modular<double> mod 319591 ... PASSED 
    Checking ...........................Modular<double> mod 293 ... PASSED 
    Checking ......................Modular<double> mod 60328897 ... PASSED 
    Checking ................ModularBalanced<double> mod 319591 ... PASSED 
    Checking ...................ModularBalanced<double> mod 293 ... PASSED 
    Checking ...........ModularBalanced<double> mod 6.03289e+07 ... PASSED 
    Checking ............................Modular<float> mod 359 ... PASSED 
    Checking ..............................Modular<float> mod 7 ... PASSED 
    Checking ...........................Modular<float> mod 1979 ... PASSED 
    Checking ....................ModularBalanced<float> mod 359 ... PASSED 
    Checking .....................ModularBalanced<float> mod 23 ... PASSED 
    Checking ...................ModularBalanced<float> mod 3001 ... PASSED 
    Checking ............Modular<int32_t, uint32_t> modulo 2143 ... PASSED 
    Checking ..............Modular<int32_t, uint32_t> modulo 23 ... PASSED 
    Checking ...........Modular<int32_t, uint32_t> modulo 19391 ... PASSED 
    Checking .................ModularBalanced<int32_t> mod 2143 ... PASSED 
    Checking ...................ModularBalanced<int32_t> mod 41 ... PASSED 
    Checking ................ModularBalanced<int32_t> mod 35771 ... PASSED 
    Checking ..........Modular<int64_t, int64_t> modulo 7397473 ... PASSED 
    Checking ..............Modular<int64_t, int64_t> modulo 547 ... PASSED 
    Checking .......Modular<int64_t, int64_t> modulo 2140703671 ... PASSED 
    Checking .............ModularBalanced<int64_t> mod 15786083 ... PASSED 
    Checking ..................ModularBalanced<int64_t> mod 547 ... PASSED 
    Checking ...........ModularBalanced<int64_t> mod 4288187317 ... PASSED 
    Checking Modular<[IntType]> modulo 128955835551184936203732457918559215561 ... PASSED 
    Checking Modular<[IntType]> modulo 92724916935990612858234730122164910499 ... PASSED 
    Checking Modular<[IntType]> modulo 108292956889227064445761891442502437723 ... PASSED 
    Checking Modular<RecInt::ruint<7>, RecInt::ruint<8>> modulo 128955835551184936203732457918559215561 ... FAIL
    alpha   :1, beta   : 0
    m   :3, k   : 3
    ldA :9, incX : 6, incY : 12
    Error Y[0]=54618784186693597154044789541075290685 D[0]=99308746885162063093594100985169760632
    Error Y[1]=84046523840635807248684154302256168012 D[1]=44330885234184674621457790586566214292
    Error Y[2]=66837268538333704444593484166744705459 D[2]=41626482411164455219278824135286617775
    XXX
    FAILED 
    FAIL test-fgemv (exit status: 1)

**Comment by ClementPernet** [comment]
Thanks for the report.
variant for fgemm (using `Modular<ruint<K>,ruint<K+1> >` and its conversion to RNS) was introduced in 2098ef3ebd5723c2e655f7e37027527a43d5279b .
It is likely related to file `field/rns-double-recint.inl` where I see some endianness dependent code.
I checked the log in the link of the failing builds, and they all indicate that the architecture was correctly found to be big endian, so the macor ` __FFLASFFPACK_HAVE_BIG_ENDIAN` should be set correctly.
I assign @pascalgiorgi to the issue, as he is the author of this code.

**Comment by cyrilbouvier** [comment]
After looking at https://buildd.debian.org/status/logs.php?pkg=fflas-ffpack&ver=2.3.2-1~exp1, I think the bug comes from the combination big endian & 32 bit architecture:
 - sparc64 (big endian & 64 bit architecture) fails but for differents reasons.
 - powerpcspe and m68k (big endian & 32 bit architecture) pass but `make check` is not run
- once the three archs are removed, there is a bijection between failure and big endian & 32 bit architecture.

I suspect the problem come from the use of `mp_limb_t` which is (always?) an `unsigned int`. However RecInt::recuint use `uint64_t` for storage. On 32-bit arch with big endian, lines like
```cpp
A_beta[l+idx*k]= m0_ptr[l^((sizeof(mp_limb_t)/2U)-1U)];
```
may not do what is expected.

**Comment by ClementPernet** [comment]
Fixed since #186 was merged
