### ISSUE TITLE
Instalation issue- Documentation could be improved

### ISSUE THREAD

**Issue by LyesHamlatIT** [linbox-team/fflas-ffpack#161]
The configure file is generated automatically by "autogen.sh" and this is not mentioned in the doc. It will save a lot of time for beginners if you could mention that in the documentation.

Many thanks,
Lyes

**Comment by P1K** [comment]
`README` now includes the message:

> if you are compiling the upstream git master branch, juste replace `configure` by `autogen.sh` in the above command: the configure script will be auto-generated and run with the arguments passed to `autogen.sh`
