### ISSUE TITLE
Don't sort CXXFLAGS

### ISSUE THREAD

**Issue by isuruf** [linbox-team/fflas-ffpack#166]
There are CXXFLAGS that need to be one after another.
For eg:
```
  -arch x86_64                         (on MacOSX to set the architecture)
  -I /path/to/directory                (equivalent to -I/path/to/directory, but valid)
```
See https://github.com/linbox-team/fflas-ffpack/blob/451f68208ce000be9067d948bc1d36e5b2358d0d/configure.ac#L310

cc @saraedum

**Comment by ClementPernet** [comment]
Fixed by ecc33bc
