### ISSUE TITLE
SIMD capabilities detected at configure are not enforced during compilation

### ISSUE THREAD

**Issue by cyrilbouvier** [linbox-team/fflas-ffpack#184]
While looking at #182, I looked at the detection code of SIMD capabilities by the configure script and found that what is printed by the configure script (SSE disabled/enabled, ...) is not always enforced during compilation.

The following is based on commit 3f4e366 (Oct 2nd) on the master branch.

During configure, the user can control which SIMD instructions are used with command line parameters such as `--disable-sse`, `--disable-avx`, ... (configure.ac call `INSTR_SET` which is defined in [macros/instr_set.m4](../blob/3f4e366/macros/instr_set.m4)). The available instructions sets are detected with [macros/CodeChunk/instrset.h](../blob/3f4e366/macros/CodeChunk/instrset.h) and [macros/CodeChunk/instrset_detect.cpp](../blob/3f4e366/macros/CodeChunk/instrset_detect.cpp). There are 3 cases:

1. if the command line parameter `disable-*` is used, nothing is done: the idea is that this set of instructions is "disabled";

2. if the command line parameter is not used and that the instructions set is detected as unavailable, nothing is done;

3. if the command line parameter is not used and that the instructions set is detected as available, the corresponding flag is added in `SIMD_CFLAGS` (for example `-msse` is added for SSE instructions). The variable `SIMD_CFLAGS` in appended to `CXXFLAGS` at the end of configure, which is used in the different Makefile.am of the project.

During the compilation, the important file is [fflas-ffpack/fflas-ffpack-config.h](../blob/3f4e366/fflas-ffpack/fflas-ffpack-config.h) which is included by [fflas-ffpack/fflas-ffpack.h](../blob/3f4e366/fflas-ffpack/fflas-ffpack.h). This file define the macros `__FFLASFFPACK_HAVE_*_INSTRUCTIONS` which are used to protect code using special instructions. These macros are defined using compiler-defined macros such as `__SSE__`, `__SSE2__`, `__AVX__`, ... which are defined by the compiler depending on the use of command line parameters such as `-msse`, `-msse2`, `-mavx`. But, and part of the problem is here, some macros are defined by default by the compiler. For example, on my computer, with Intel Core I5 (with SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, AVX, AVX2 and FMA3 capabilities) and g++ 8.2
```
$ gcc -dM -E - < /dev/null | grep -e SSE -e AVX -e FMA | sort
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE_MATH__ 1
```

As fflas-ffpack is a header library, `make` and `make install` does not compile any code. Thus, sometimes, there is no link between the instructions marked as enable/disable by the configure script and what is actually compiled and used.

Let look at what can happen, on a computer such that the default macros defined by the compiler are
```
$ gcc -dM -E - < /dev/null | grep -e SSE -e AVX -e FMA | sort
#define __SSE__ 1
#define __SSE2__ 1
#define __SSE2_MATH__ 1
#define __SSE_MATH__ 1
```
and where fflas-ffpack is configure with disabling everything except SSE and AVX
```
$ ./configure --disable-sse2 --disable-sse3 --disable-ssse3 --disable-sse41 --disable-sse42 --disable-avx2 --disable-avx512f --disable-avx512dq --disable-fma --disable-fma4
```

The configure script output
```
Detecting SIMD instruction set
SSE enabled
SSE2 disabled
SSE3 disabled
SSSE3 disabled
SSE4.1 disabled
SSE4.2 disabled
AVX enabled
AVX2 disabled
AVX512F disabled
AVX512DQ disabled
FMA3 disabled
FMA4 disabled
```
and `CXXFLAGS` contains `-msse -mavx`.

Depending on how fflas-ffpack is used/compiled, this induces different behavior. If fflas-ffpack is used/compiled

1. by using `make check` or `make examples` (i.e., via any make command that is defined in a Makefile.am). `CXXFLAGS` with `-msse -mavx` will be passed to the compiler, but fflas-ffpack will use SSE, __SSE2__ and AVX because, by default, the compiler defined `__SSE2__`. So the argument `--disable-sse2` of configure is not respected. 

2. by using `pkg-config --cflags fflas-ffpack`. The fflas-ffpack.pc file does not contains `CXXFLAGS` but a subset of it that does not contains `SIMD_CFLAGS` (see linbox-team/givaro#22). So it will be compiled without any flags related to SIMD instructions and it will use the default macros set by the compiler (SSE and SSE2 in this example). So the argument `--disable-sse2` of configure is not respected and the AVX instructions which were said to be enabled are not used.

3. by using `fflas-ffpack-config --cflags`. This includes `CXXFLAGS`, so the behavior will be the same as 1.

4. directly via a command line like `g++ ...`. In this case, the user can provide any arguments s/he wants during the compilation. This can result in any behavior: using instructions that were said to be disabled, not using ones that were said to be enabled. Nothing from configure can be enforced in this case.

What can be done:

- do not detect SIMD instructions and let the users choose the instructions set at compile time via the arguments of the compiler. This means that most of the time only the default macros set by the compiler will be available.

- making `fflas-ffpack/fflas-ffpack-config.h` a `.in` file in which only the macros `__FFLASFFPACK_HAVE_*_INSTRUCTIONS` corresponding to what was enabled/disabled at configure time are set.

- setting `CXXFLAGS` at configure with the capabilities asked by the user (with `-m*` to enable and `-mno-*` to disable), but allow the user to use other arguments later.

Regarding, Givaro the problems are almost the same as the only code that use SIMD instructions is inside an `.inl` file and thus not compiled when `make` is run on the Givaro project. I will edit this post with the differences between the cases of Givaro and fflas-ffpack.

P.S. Some remarks that are not part of the problem but are related to SIMD detection by configure:

- for SSE, and only for SSE, the variable `HAVE_SSE` is set, but is never used elsewhere and never exported;

- the flags are written in `SIMD_CFLAGS` but the exported variable is `SIMD_FLAGS` (via `AC_SUBST` in [configure.ac](../blob/3f4e366/configure.ac#L177) line 177) so the `SIMD_CFLAGS` in unusable in Makefile.am as it is not exported and the `SIMD_FLAGS` is always empty. At the end of configure, it is the correct variable `SIMD_CFLAGS` which is appended to `CXXFLAGS`.

- the two files [macros/sse2-check.m4](../blob/3f4e366/macros/sse2-check.m4) and [macros/simd-check.m4](../blob/3f4e366/macros/simd-check.m4) does not seem to be used.

**Comment by cyrilbouvier** [comment]
Two other remarks:

1. The list of macros `__FFLASFFPACK_HAVE_*_INSTRUCTIONS` defined in [fflas-ffpack/fflas-ffpack-config.h](../blob/master/fflas-ffpack/fflas-ffpack-config.h) does not correspond exactly to the list of arguments of configure:

  - the macros are `__FFLASFFPACK_HAVE_*_INSTRUCTIONS` where the `*` can be SSE, SSE2, SSE3, SSE4_1, SSE4_2, AVX, AVX2, AVX512F, AVx512DQ (is the small x a typo ?), FMA.
 
  - the arguments of configure are `--disable-*` with `*` can be sse, sse2, sse3, ssse3, sse41, sse42, avx, avx2, avx512f, avx512dq, fma, fma4 (ssse3 and fma4 have no equivalent macros)

2. some arguments like `-msse*` are implied by other. For example, on my machine compiling with `g++ -mavx` implicitly defined `-msse -msse2 -msse3 -msse4`. So if I run configure with `--disable-sse`, as the configure script will add `-mavx` to `CXXFLAGS` (because AVX will be detected on my machine), the code will be compiled with SSE instructions when I compile with `make` or `fflas-ffpack-config`. If the configure script is tasked with settings the SIMD capabilities, it should warn against incompatible requests.

**Comment by ClementPernet** [comment]
Thanks Cyril for this in-depth review and bug chase.
I'm the one to blame for these problems, and am happy to help fixing them, once we agree on a way to go.
Let me first comment on a few points you raised:
>This file define the macros `__FFLASFFPACK_HAVE_*_INSTRUCTIONS` which are used to protect code using special instructions. These macros are defined using compiler-defined macros such as `__SSE__`, `__SSE2__`, `__AVX__`, ... which are defined by the compiler depending on the use of command line parameters such as `-msse`, `-msse2`, `-mavx`. But, and part of the problem is here, some macros are defined by default by the compiler. For example, on my computer, with Intel Core I5 (with SSE, SSE2, SSE3, SSSE3, SSE4.1, SSE4.2, AVX, AVX2 and FMA3 capabilities) and g++ 8.2
> 
> ```
> $ gcc -dM -E - < /dev/null | grep -e SSE -e AVX -e FMA | sort
> #define __SSE__ 1
> #define __SSE2__ 1
> #define __SSE2_MATH__ 1
> #define __SSE_MATH__ 1
> ```
>

This is a flaw in the design indeed. I assumed that every compiler macro __SSE__ or __AVX__ was set when the related -msse or -mavx option was passed. This is not true for SSE and SSE2, but still holds for AVX, AVX2 and AVX512F AVX512DQ.
I think this is related to the assumption by gcc that any x86_64 or i386 must have SSE2 at least (I can't remember where I read that).

> As fflas-ffpack is a header library, `make` and `make install` does not compile any code. Thus, sometimes, there is no link between the instructions marked as enable/disable by the configure script and what is actually compiled and used.
Not entirely true: one need to keep in mind the scenario where `--enable-precompilation` option has been passed to configure, where the standard template specialization are precompiled in a lib, speeding-up other compilations.
> 
> What can be done:
> 
>     * do not detect SIMD instructions and let the users choose the instructions set at compile time via the arguments of the compiler. This means that most of the time only the default macros set by the compiler will be available.
> 
This would only work in the "source-only mode".

>     * making `fflas-ffpack/fflas-ffpack-config.h` a `.in` file in which only the macros `__FFLASFFPACK_HAVE_*_INSTRUCTIONS` corresponding to what was enabled/disabled at configure time are set.
> 
Maybe a good way to go

>     * setting `CXXFLAGS` at configure with the capabilities asked by the user (with `-m*` to enable and `-mno-*` to disable), but allow the user to use other arguments later.
>
This seems too low level to me: these options vary depending on the compiler (not alway a -mXXX option), so I'm not super happy with it and prefer autodetect+ ability to disable. 

>     * for SSE, and only for SSE, the variable `HAVE_SSE` is set, but is never used elsewhere and never exported;
Indeed, more case are handled than the one we need. Just for the sake of completeness.
> 
>     * the flags are written in `SIMD_CFLAGS` but the exported variable is `SIMD_FLAGS` (via `AC_SUBST` in [configure.ac](../blob/3f4e366/configure.ac#L177) line 177) so the `SIMD_CFLAGS` in unusable in Makefile.am as it is not exported and the `SIMD_FLAGS` is always empty. At the end of configure, it is the correct variable `SIMD_CFLAGS` which is appended to `CXXFLAGS`.
> 
Oups, this is a bad one.
>     * the two files [macros/sse2-check.m4](../blob/3f4e366/macros/sse2-check.m4) and [macros/simd-check.m4](../blob/3f4e366/macros/simd-check.m4) does not seem to be used.
These were the former files for autodetect that I dropped when I wrote this machinery. I did not want to remove them before a while, in case we would need them back. They probably should be removed now.

**Comment by cyrilbouvier** [comment]
> Not entirely true: one need to keep in mind the scenario where --enable-precompilation option has been passed to configure, where the standard template specialization are precompiled in a lib, speeding-up other compilations.

Indeed, I forgot this case. As the compilation is handled by a Makefile of the fflas-ffpack project, I assume the behavior is similar to the cases 1 and 3 of my first ticket.

------

If the configure script should handle the flags regarding SIMD capabilities, the following problems arised:

1. do we autodetect the capabilities or do we use the default setting of the compiler ?

2. if we allow the user to enable/disable certains instructions sets, how do we check that correctness of the settings ?
For example, on my machine, I cannot compile the simplest program without SSE:
```cpp
#include <cstdlib>

int
main (int argc, char *argv[])
{
  return 0;
}
```
The command `g++ -mno-sse nosse.cpp -o nosse` fails with `error: SSE register return with SSE disabled`. It does not seem to be a bug of gcc, more a undocumented behavior, see [gcc bug tracker](https://gcc.gnu.org/bugzilla/show_bug.cgi?id=46716) where someone says "Basically, the 64-bit calling convention support assumes that the SSE2 instructions are always available". I am not sure if it is easy to check this kind of thing.

3. if we allow the user to enable/disable certains instructions sets, how do we check that what the user asked is what is actually done by the compiler. For example, on my computer, using `-mavx` with g++ implicitly sets `-msse -msse2 -msse3 ...`. So a user configure fflas-ffpack with `--disable-sse`, as the configure script autodetect AVX, it will add `-mavx` into `SIMD_CFLAGS` and SSE will not be disabled.

4. what is the point of setting the compiler options for SIMD if they are not exported in the .pc file and thus not used by other programs/libraries using fflas-ffpack? For example, linbox detect fflas-ffpack with pkg-config, so it will not know what `-m*` was set during configure of fflas-ffpack. (Note that this is also true for the givaro/fflas-ffpack relationship).

-----

Note that a user can always change the value of the `CXXFLAGS` on the make command line by typing for example:
```
make CXXFLAGS="-mavx" check
```
but it completly replaces the value of `CXXFLAGS` which contains other flags not related to the SIMD configuration. I found no way to append or prepend flags to `CXXFLAGS`.

**Comment by cyrilbouvier** [comment]
After reading and writing code using SIMD in FFLAS and Linbox, here what I propose regarding this issue:

1. Remove any configure-time detection of SSE, AVX, ...; do everything at compile time in FFLAS
2. The main part of detecting what is avalaible should be done in `fflas-ffpack/fflas/fflas_simd.h` and the `fflas-ffpack/fflas/fflas_simd` directory. The detection code could be inspired by the code currently used during configure: `macros/CodeChunk/instrset_detect.cpp`.
3. Currently `fflas_simd.h` define some classe `NoSimd`, `Simd128`, .... The class `Simd128<Type>` is defined only if 128-bit-wide SIMD is available for this type. I think it should always be defined and have a constant static boolean method `::is_available` to check during compilation. The gaol if to remove all the `#define __XXX_HAVE_SSE`, `__XXX_HAVE_AVX` in the code, which can easily be misused (which macro exactly should be used for a particular type is not easy to find) and replace by `enable_if<Simd128<Type>::is_available>` or `if (Simd128<Type>::is_available)` in the code.

What do you think ?
Should I start trying this approch ?

**Comment by cyrilbouvier** [comment]
- disabling some instruction sets could still be achieved with a command line like:
```
CXXFLAGS="-noavx -noavx2" ./configure
```
At configure time, we could only check that flags given in CXXFLAGS are coherent (meaning that they can be used to compile a empty program).

- If some SIMD instructions are used in Givaro, why not move the code from the `fflas_simd` directory  into Givaro ?
As I understand, currently, the code of `Givaro::ModularExtended::mul` does not use any macros defined at configure: it uses `FP_FAST_FMAF` and `__SSE_MATH__`. Moreover some other code in `Givaro::ModularExtended` use `__GIVARO_HAVE_SSE_INSTRUCTIONS` which is never defined.

**Comment by cyrilbouvier** [comment]
Moreover, if i am not mistaken, the file `src/kernel/ring/modular-extended.inl` is not compiled into the givaro library, so libgivaro can be compiled without any knowledge of the available simd instruction sets.

Here what i think should be done for Givaro, so far:
- remove detection of SIMD instructions
- prepend `-marchive=native` to CXXFLAGS (this defined all flags corresponding to all SIMD instructions available on the machine, as `FP_FAST_FMAF` and `__SSE_MATH__`) (this may prevent cross compiling, do we care ?)

The consequences will be:
- libgivaro will be compile with `-marchive=native`. As no SIMD-specific instructions are used in the library (is it correct ?), libgivaro will still be usable on machives where less SIMD instructions are available.
- tests, benchmarks and examples will be compile with `-marchive=native` so they will use all SIMD instructions available on the machine where the compilation takes place.

Note that for the experienced user, it is still possible to disable SIMD instructions by calling, for example,
```
CXXFLAGS="-noavx -noavx2" ./configure
```
if those flags are added **after** `-marchive=native` in the variable that is set by the configure script.

There is one question that I do not know how to answer: should `marchive=native` be written in `givaro.pc` ? Is it debian-compliant ?


What do you think about this setting ?

I am still thinking about what can be done for fflas and linbox.

**Comment by P1K** [comment]
The changes discussed in this issue have been implemented, so I'm closing it
