### ISSUE TITLE
simd128_int64 fails to compile on OSX

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#20]
See
https://ci.inria.fr/linbox/job/FFLAS-FFPACK-clang++/51/label=linbox-osx-amd64/artifact/config.log

@romainlebreton : you seem to have last edited this line of code (simd128_int64.inl:605)

**Comment by romainlebreton** [comment]
@pascalgiorgi Problem is with uint128_t macro defined in fflas-ffpack-config.h . Since you have a clang compiler on your OSX, can you take a look please ?

**Comment by romainlebreton** [comment]
@pascalgiorgi I have installed clang on my computer and have been able to fix one error (uint128_t) and some warnings. It remains some error with the intrinsics _mm_shuffle_epi32 that I don't understand yet

**Comment by romainlebreton** [comment]
@pascalgiorgi @ClementPernet The remaining error is on some of my code that is not on the master branch so everything should be OK.
