### ISSUE TITLE
Simd512 files are not installed during make install

### ISSUE THREAD

**Issue by BastienVialla** [linbox-team/fflas-ffpack#202]
Hey, happy new year,

During the `make install` the Simd512 files are not installed.
The files are missing in the [`Makefile.am`](https://github.com/linbox-team/fflas-ffpack/blob/master/fflas-ffpack/fflas/fflas_simd/Makefile.am) from the fflas_simd folder.

**Comment by ClementPernet** [comment]
Thanks Bastien for the report.
It's now fixed since d760974129e4a6d8a739c93df99adc96c8c6a374
