### ISSUE TITLE
--enable-sse flag : sse enabled by default(?) => flag should be named `--disable-sse`

### ISSUE THREAD

**Issue by jakobkroeker** [linbox-team/fflas-ffpack#21]
the configure script of fflas_ffpack has a flag `--enable-sse`
Im not very familiar with M4 scripts, but Dan Grayson claims that sse is enabled by default.
If that is indeed the case, should then the  flag be named `--disable-sse` instead of `enable-sse`?

See also the ticket https://github.com/Macaulay2/M2/issues/462
for problems building fflas_ffpack on a X200 lenovo tablet.

update: same holds for `--enable-avx` flag

**Comment by ClementPernet** [comment]
fixed in 173b1f3fd0708183abfd43750ad59fcd5924d2f1
