### ISSUE TITLE
test-simd fails on OSX

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#219]
See 
https://ci.inria.fr/linbox/view/LinBox%20ecosystem/job/FFLAS-FFPACK/Archi=linbox-osx,Compiler=clang++/402/PerfPublisher/testDetails.test-simd/

**Comment by ClementPernet** [comment]
Note that this only shows up now since, earlier the test just did not compile!

**Comment by cyrilbouvier** [comment]
Weird, all inputs are printed as `inf` !
I will try to look into it.

**Comment by P1K** [comment]
This seems to be only a recent issue, as I had no problem with test-simd on OSX until pulling the most recent master.
But now it doesn't even compile, OSX or not:
```
test-simd.C:373:18: error: no member named 'mulhi' in 'Simd128_impl<true, true, true, 8>'
```

**Comment by cyrilbouvier** [comment]
> But now it doesn't even compile, OSX or not:

```
test-simd.C:373:18: error: no member named 'mulhi' in 'Simd128_impl<true, true, true, 8>'
```

`mulhi` implementation is protected by `__FFLASFFPACK_HAVE_INT128` in `simd128_int64.inl`.
Is it linked to linbox-team/givaro#95 ?

In any case, they should be a fallback. You can open another issue and assign it to me.

**Comment by P1K** [comment]
Okay, #221 fixes this on the two builds I currently have:
* OSX, AVX2
* Ubuntu, AVX512
