### ISSUE TITLE
msse4.1 compatibility check too optimistic?

### ISSUE THREAD

**Issue by jakobkroeker** [linbox-team/fflas-ffpack#22]
on my machine (X200 lenovo) with fedora 23  the `fflas_ffpack` detects msse
`SSE 4.1... yes (SSE)`

but then Macaulay2 does not compile at places where `fflas_ffpack`  is used,
see https://github.com/Macaulay2/M2/issues/462

Question: is the SSE 4.1 check too optimistic?
If yes, could you fix it?

**Comment by ClementPernet** [comment]
It seems that the compilation failure in [Macaulay2/M2#462](https://github.com/Macaulay2/M2/issues/462) is indeed related to sse4.1 not being supported on this system (`_mm_round_ps` was introduced in the sse4.1 std).

Still the SSE4.1 check should not be too optimistic as it tries compile another SSE4.1 specific intrinsic: `_mm_floor_pd`

What does /proc/cpuinfo tells you on this box ?
can you run `gcc  -msse4.1 fflas-ffpack/macro/CodeChunck/sse.C` on this box and let me know if it compiles?

**Comment by jakobkroeker** [comment]
```
[jakob@localhost fflas-ffpack-2.2.1]$ gcc -msse4.1 macros/CodeChunk/sse.C
# it compiles!
[jakob@localhost fflas-ffpack-2.2.1]$ cat /proc/cpuinfo 
processor	: 0
vendor_id	: GenuineIntel
cpu family	: 6
model		: 23
model name	: Intel(R) Core(TM)2 Duo CPU     L9400  @ 1.86GHz
stepping	: 10
microcode	: 0xa0b
cpu MHz		: 800.000
cache size	: 6144 KB
physical id	: 0
siblings	: 2
core id		: 0
cpu cores	: 2
apicid		: 0
initial apicid	: 0
fpu		: yes
fpu_exception	: yes
cpuid level	: 13
wp		: yes
flags		: fpu vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush dts acpi mmx fxsr sse sse2 ss ht tm pbe syscall nx lm constant_tsc arch_perfmon pebs bts nopl aperfmperf pni dtes64 monitor ds_cpl vmx smx est tm2 ssse3 cx16 xtpr pdcm sse4_1 xsave lahf_lm ida dtherm tpr_shadow vnmi flexpriority
bugs		:
bogomips	: 3723.80
clflush size	: 64
cache_alignment	: 64
address sizes	: 36 bits physical, 48 bits virtual
power management:
# cut output here
[jakob@localhost fflas-ffpack-2.2.1]$ 
```
so you are right, the sse4_1 is correctly detected but there must be a different problem then..

closing as invalid...

**Comment by ClementPernet** [comment]
To be perfectly correct: CodeChunck/sse.C should always compile with -msse4.1, eventhough the computer does not support sse4.1.
But the running it should throw an `illegal instruction` which will be catched by the configure script.
I tested it successfully on a Xeon 5310 (clovertown)  without sse4.1, running a debian.
