### ISSUE TITLE
Standard interface for Sequential/Parallel switch in FFPACK

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#228]
First, PLUQ interface should have a similar switch between Sequential and Parallel modes as FFLAS::fgemm: using ParSeqHelpers. This is already the topic of #36 .
Then other FFPACK routines, such as Det, Rank, solve, Echelon-forms, etc rely on LUdivine or PLUQ and could therefore directly benefit from its parallel version. 
Workplan:

- [x] fix #36 : add a ParSeqHelper argument to pluq, with default value Sequential, and rename ppluq pluq (...., ParSeqHelper::Parallel<Recursive,Threads>)
 add a template ParSeqHelper argument to Det
 - [x] Det, 
 - [x] Rank, 
 - [x] Solve, 
 - [x] Echelon, 
etc and forward it to PLUQ

**Comment by ZHG2017** [comment]
Some tests will fail if switching from LUdivine to PLUQ in the Rank function so the adaptation of Rank is on hold for now.

**Comment by ClementPernet** [comment]
What do you mean ? Rank uses PLUQ on master and all tests pass.

**Comment by ZHG2017** [comment]
I have just found out the problem, I did not update with the master branch which caused some tests' failure. I used the previous master branch version instead of the current one which has  merged with templated PLUQ.

**Comment by ClementPernet** [comment]
Solved by #246 #245 #240 #241 #237 #235 #233 #231 #229
