### ISSUE TITLE
Rank error in PLUQ basecase crout ?

### ISSUE THREAD

**Issue by ash09** [linbox-team/fflas-ffpack#24]
Iam giving a rank 3 matrix,
but crout says rank 4:
--------
Computing PLUQ...
A:=Matrix(5,4,
[[0, 2, 2, 0 ],[0, 2, 1, 2 ],[0, 1, 2, 1 ],[0, 1, 4, 1 ],[0, 0, 2, 1 ]]);;
croutrank:4
P:=[ 0 1 2 3 ]

L,U:=Matrix(5,4,
[[2, 2, 0, 0 ],[1, 4, 2, 2 ],[3, 4, 3, 4 ],[3, 2, 4, 3 ],[0, 0, 2, 1 ]]);;
Q:=[ 1 2 3 4 4 ]
----------
when re applying L*U, the last column is not the zero column ...
Thanks,

**Comment by ClementPernet** [comment]
Can you be a bit more specific: 
- what field ?
- what are the arguments to your call to PLUQ ?
I ran the following code:
```c++
double  A[20] = {0, 2, 2, 0 , 0, 2, 1, 2 , 0, 1, 2, 1 , 0, 1, 4, 1 , 0, 0, 2, 1};
	size_t * P = new size_t[5];
	size_t * Q = new size_t[4];
	size_t R = FFPACK::PLUQ_basecaseCrout (F, FFLAS::FflasNonUnit, 5, 4, A, 4, P, Q);
	std::cerr<<"R="<<R<<std::endl;
	delete[] P;
	delete[] Q;
```
which return R=3 as expected

**Comment by jgdumas** [comment]
p=5

**Comment by ClementPernet** [comment]
Sure, I figured it from the matrix values. My working example is over Z5Z too. Which field are you using?Please copy the code being run.

**Comment by ash09** [comment]
Oups, sorry, my bad, a printing error (parameter id in write_field).
Thanks,
