### ISSUE TITLE
test-echelon fails

### ISSUE THREAD

**Issue by isuruf** [linbox-team/fflas-ffpack#267]
I'm checking fflas-ffpack 2.4.1 and using Reference LAPACK implementation (netlib one).

test-echelon fails on both linux and osx.

`
Checking .........Modular<double> modulo 66753079 ...........FAIL (column echelon LuTag=1)
`

Full error log at https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=41129&view=logs

This doesn't happen in 2.4.0.

**Comment by jamesjer** [comment]
I also see this failure with openblas on an x86_64 box running Fedora Rawhide.

**Comment by ClementPernet** [comment]
Thanks for the report.
I fixed the issue in d54106c (the test suite was not updated wrt the new API for the parallel echelon routines).
I also release v2.4.2 with this upgrade.

**Comment by isuruf** [comment]
Thanks for the bugfix. v2.4.2 passes all tests
