### ISSUE TITLE
intrinsic _mm_bslli_si128 not supported with clang <=3.6.1

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#27]
This makes the whole test-suite fail with any such clang.

[See here for example.](https://ci.inria.fr/linbox/job/FFLAS-FFPACK-clang++/label=linbox-ubuntu-amd64-icpc-clang/87/PerfPublisher/testDetails.benchmark-fgemm/)

This is a rather old intrinsic (SSE2) but clang seems to only support it is since Feb 2015 (probably v 3.6.1 and later) [http://permalink.gmane.org/gmane.comp.compilers.clang.scm/116677]

Hence we should have a fall back disabling this intrinsic when clang is detected to have a version older than 3.6.1.

**Comment by romainlebreton** [comment]
Since _mm_bslli_si128 was just an alias for _mm_slli_si128, I just skipped the alias. Should be fixed in
https://github.com/linbox-team/fflas-ffpack/commit/fbf7396d3561a7e3e55339936af2918b4e6e8e96 also I did not test it.
