### ISSUE TITLE
configure: BLAS not found

### ISSUE THREAD

**Issue by ChristophDl** [linbox-team/fflas-ffpack#277]
Hi,

I have tried a lot to configure fflas-ffpack with my installed OpenBLAS version, without success. The error is

checking for BLAS... problem
ERROR: BLAS not found!

I do not have sudo permissions and therefore setting the flags correctly seems to be the problem.

I have tried:

./configure --with-blas-libs="-lopenblas" PKG_CONFIG_PATH=/home/Packages/linboxall/givaroinstall/lib/pkgconfig --prefix=/home/Packages/linboxall/fflasffpackinstall

and

./configure --with-blas-libs="/home/Packages/linboxall/OpenBLASinstall/lib/libopenblas.so" --with-blas-cflags=/home/Packages/linboxall/OpenBLASinstall/include PKG_CONFIG_PATH=/home/Packages/linboxall/givaroinstall/lib/pkgconfig --prefix=/home/Packages/linboxall/fflasffpackinstall

and

./configure --with-blas-libs="-L/home/Packages/linboxall/OpenBLASinstall/lib/libopenblas.so" --with-blas-cflags=/home/Packages/linboxall/OpenBLASinstall/include PKG_CONFIG_PATH=/home/Packages/linboxall/givaroinstall/lib/pkgconfig:/home/Packages/linboxall/OpenBLASinstall/lib/pkgconfig --prefix=/home/Packages/linboxall/fflasffpackinstall

Also, my .bash_profile includes

export PATH="/home/Packages/linboxall/givaroinstall/include:$PATH"
export LD_LIBRARY_PATH="/home/Packages/linboxall/givaroinstall/lib:$LD_LIBRARY_PATH"
export PATH="/home/Packages/linboxall/OpenBLASinstall/include:$PATH"
export LD_LIBRARY_PATH="/home/Packages/linboxall/OpenBLASinstall/lib:$LD_LIBRARY_PATH"

which also didn't help.

Thanks in advance!

Christoph

P.S.: I would also like to point out, that the version does not come with a configure script and the installation instructions do not say how to obtain one. It took me some time to find out that I had to use autoreconf. Also, <libs> and <cflags> does not tell me anything and it also took me quite a lot of time to find out what paths I have to insert here (and I am still not sure if they are correct).

**Comment by Breush** [comment]
Hi @ChristophDl,

You might want to try to configure with `--with-blas-libs="-L/home/Packages/linboxall/OpenBLASinstall/lib -lopenblas" --with-blas-cflags="-I/home/Packages/linboxall/OpenBLASinstall/include"`.
But as you said you exported the PATH and LD_LIBRARY_PATH, I have the feeling that this might not work.

If that's does not solve your problem, you should have a look at this script https://github.com/linbox-team/linbox/blob/master/linbox-auto-install.sh within the LinBox repository, which has a `--enable-openblas` option to download it for you and install givaro/fflas/linbox accordingly.

BTW, you can check `config.log` to see why `ERROR: BLAS not found!` has been emitted.

**Comment by ChristophDl** [comment]
@Breush 

Thanks a lot, changing the flags did the trick:

`./configure --with-blas-libs="-L/home/Packages/linboxall/OpenBLASinstall/lib -lopenblas" --with-blas-cflags="-I/home/Packages/linboxall/OpenBLASinstall/include" PKG_CONFIG_PATH=/home/Packages/linboxall/givaroinstall/lib/pkgconfig --prefix=/home/Packages/linboxall/fflasffpackinstalll`

This should definitely be in the installation instructions!
