### ISSUE TITLE
unsupported instruction `vmovdqu'

### ISSUE THREAD

**Issue by timokau** [linbox-team/fflas-ffpack#284]
The fflas-ffpack build on our (NixOS) build server recently failed during the test phase with the following error:

```
make  check-TESTS
make[3]: Entering directory '/build/source/tests'
make[4]: Entering directory '/build/source/tests'
g++ -DHAVE_CONFIG_H -I. -I..    -O2  -Wall -g  -I..  -fabi-version=6  -msse -msse2 -mavx512f -mavx512vl -mavx512dq -fabi-version=6 -I/nix/store/hvp2g7haqfypign9wq0fif6p70k5ks5k-givaro-4.1.1/include   -fopenmp -c -o test-fdot.o test-fdot.C
g++ -DHAVE_CONFIG_H -I. -I..    -O2  -Wall -g  -I..  -fabi-version=6  -msse -msse2 -mavx512f -mavx512vl -mavx512dq -fabi-version=6 -I/nix/store/hvp2g7haqfypign9wq0fif6p70k5ks5k-givaro-4.1.1/include   -fopenmp -c -o test-finit.o test-finit.C
g++ -DHAVE_CONFIG_H -I. -I..    -O2  -Wall -g  -I..  -fabi-version=6  -msse -msse2 -mavx512f -mavx512vl -mavx512dq -fabi-version=6 -I/nix/store/hvp2g7haqfypign9wq0fif6p70k5ks5k-givaro-4.1.1/include   -fopenmp -c -o test-fscal.o test-fscal.C
/build/cc8a6v2g.s: Assembler messages:
/build/cc8a6v2g.s:109811: Error: unsupported instruction `vmovdqu'
/build/cc8a6v2g.s:109838: Error: unsupported instruction `vmovdqu'
```

If I read [this](https://hjlebbink.github.io/x86doc/html/MOVDQU,VMOVDQU8_16_32_64.html) page right, `vmovdqu` is part of the `avx` feature set, which we've disabled with `--disable-avx`. You can see the full log [here](https://github.com/linbox-team/fflas-ffpack/files/3651345/fflas-ffpack-failure.log).

Is this a mistake on our side or a bug in fflas-ffpack?

**Comment by ClementPernet** [comment]
Hi,
Looking at the log and the flags handed to the compiler, it looks like you indeed disable the avx and AVX2 instructions but not the AVX512 ones. I guess fflas-ffpack incorrectly deduce that AVX is enabled by the fact that some higher level AVX set is enabled, thus causing the bug.
We should change the behaviour of these disable option to automatically disable all instruction set above.
Meanwhile, you could fix your problem adding `--disable-avx512f --disable-avx512dq --disable-avx512vl` to your configure script.

**Comment by timokau** [comment]
Thanks for looking into this so quickly! I've adopted your workaround for now.

Disabling higher versions implicitly probably makes sense, there are already [quite a few](https://github.com/NixOS/nixpkgs/blob/a82ae1470a0f49bcb26fd97afbbb09753e3146b5/pkgs/development/libraries/fflas-ffpack/default.nix#L33) flags we have to pass to disable all the sse and fma versions. From a distro perspective (since we want reproducible builds for the different architectures) it would actually probably make more sense to *white list* features instead, but https://github.com/linbox-team/fflas-ffpack/issues/285 would already be a great help.

**Comment by dimpase** [comment]
would it make sense to test in ./configure that each of these avx-related  extra flags you inject works with the compiler?

**Comment by ClementPernet** [comment]
For the record, we are currently moving away from this configure time detection for several reasons (see #184) and will only compile have `-march=native` by default unless explicitely told by the user not to do so (at config time).

**Comment by ClementPernet** [comment]
Closing as it is no longer relevant since we removed the fine grain selection of intruction sets, and use `-march=native` instead.
