### ISSUE TITLE
fgemm_mp fails with TransTrans

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#291]
bugs in test-fgemm show up frequently in all of the 3 instance
 - `Modular<Integer>
 - `ZRing<Integer>`
 - `Modular<ruint<K>>`
all of which reduce to calling the RNS based fgemm_mp.
The failure seem to only show up with `transA = FflasTrans` and `transB = FflasTrans`

Maybe related to #171

**Comment by ClementPernet** [comment]
The bug is very likely a bug in BLIS. I replaced BLIS by OpenBLAS and it suddenly vanished.
TODO (when time permits): write down a MWE. The instance in cause was
`./test-fgemm -n 11 -k 2 -m 11 -w 0 -s 673309683`
where all fields except `Modular<Integer>` were commented out and only the case alpha=1 and beta=0 was kept.

**Comment by P1K** [comment]
> The bug is very likely a bug in BLIS. I replaced BLIS by OpenBLAS and it suddenly vanished.
> TODO (when time permits): write down a MWE to report it upstream. The instance in cause was
> `./test-fgemm -n 11 -k 2 -m 11 -w 0 -s 673309683`
> where all fields except `Modular<Integer>` were commented out and only the case alpha=1 and beta=0 was kept.

This actually makes a lot of sense w.r.t. #171, which I failed to replicate earlier on `retourdest`: I'm pretty sure that I initially used BLIS on this machine and that I switched to OpenBLAS at some point.
Now checking again with BLIS I get a failure fairly quickly.
