### ISSUE TITLE
test-fgemm etc. fails with int64_t of bitsize ≈ 32

### ISSUE THREAD

**Issue by P1K** [linbox-team/fflas-ffpack#292]
While testing PR #290, I have stumbled on what seems to be an old bug, possibly related to cardinality bounds.
Essentially, `./test-fgemm -b 32` nearly fails systematically for `Modular<int64_t, int64_t>` and `ModularBalanced<int64_t>`.
This does not seem to be a recent problem; I also encounter it with fflas @ e5c98654 and givaro @ d52b8363 from September 2017, but I don't understand how it was not caught before since the random field size picked by the test frequently happen to be 32-bit long.
So maybe I missed some other cause, even though I can replicate it on two machines (one Linux, one OSX).

**Comment by ClementPernet** [comment]
This is now fixed in #290 . Still `test-fgemm -b 32` raises a bug with `Modular<RecInt<7>>` (due to RNS basis parameters)
