### ISSUE TITLE
Create an example directory

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#3]
The former tests used to take as input a matrix file and run the corresponding computation on it with 3 purposes in mind:
- test correctness
- benchmark timings
- solve a user problem

The first 2 items have now become the tests and benchmark folders.
We should address the 3rd one by creating an example folder with simple programms reading input matrices in files, deciding the best field to be used, running the computation and writing the solution in files.

**Comment by jgdumas** [comment]
Done, with a 2x2 fgemm
should be easy to add pluq examples for instance

**Comment by ClementPernet** [comment]
Actually, the 2x2 example files that you introduce are not fitting with the design proposed here.
I think an example file should simply offer the feature of running one given routine (pluq, fgemm, rank, echelon, etc) on a  matrix provided as an input file by the user.
As done in examples/pluq.C
I think that examples of code running a 2x2 case rather belong to a tutorial that we should provide either as the doxygen documentation or as a wiki page on github.

**Comment by jgdumas** [comment]
Except that "on a matrix provided as an input file by the user." introduces another difficulty that is find the correct format.
Why not leave both kinds ?

**Comment by jgdumas** [comment]
Ok created a tutorial directory with 2x2 things.
