### ISSUE TITLE
Take OMPFLAGS from environment

### ISSUE THREAD

**Issue by mahrud** [linbox-team/fflas-ffpack#309]
Using AppleClang, the option `-fopenmp` is not valid, but `-Xclang -fopenmp /path/to/libomp.dylib` is. If you could take `OMPFLAGS` from the environment, or perhaps check for a few different options in `macros/omp-check.m4`, then users could use the OpenMP optimizations in more places.

**Comment by ClementPernet** [comment]
Fixed in #332
