### ISSUE TITLE
SIMD mm_permute_pd not found

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#31]
Failure to compile the precompiled libs (on fedora, osx and ubuntu with gcc-4.8).

See [https://ci.inria.fr/linbox/view/LinBox%20ecosystem/job/FFLAS-FFPACK/Archi=linbox-ubuntu-amd64,Compiler=g++-4.8,SSE=withSSE/15/console]
Probably introduced in 9ab2e889ffecbaec7393ebdcf41e121c4abb53ad
hence assigning @romainlebreton

**Comment by romainlebreton** [comment]
The two intrinsics _mm_permute_ps and _mm_permute_pd were AVX and not SSE4.1.
Fixed in 1b5a6f657e9e7acf0822a61900eaa37bd72424b5
