### ISSUE TITLE
fflas-ffpack cannot compile with only AVX512F

### ISSUE THREAD

**Issue by cyrilbouvier** [linbox-team/fflas-ffpack#312]
The file `fflas-ffpack/fflas/fflas_simd/simd512_int64.inl` cannot be compiled if only AVX512F is available. It requires AVX512DQ to works.

The implementation of the `mod` method (around line 800) calls `Simd512<double>::mod`. But this method is only available if `__FFLASFFPACK_HAVE_AVX512DQ_INSTRUCTIONS` is defined (around line 500 in `fflas-ffpack/fflas/fflas_simd/simd512_double.inl`). This macro is only defined if `__AVX512DQ__` is defined.

**Comment by ClementPernet** [comment]
Closing as we are now using `-march=native` or user provided flags, and that there is currently no architecture with AVX512F and no AVX512DQ.
