### ISSUE TITLE
Where did the -O optim flag go?

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#315]
It seems that since the introduction of the `-march=native` flag, the `-O2` or `-O0` flags are no longer given to the compiler, resulting in an embarrasing slow-down.

**Comment by cyrilbouvier** [comment]
The "-O" flags is set by SET_FLAGS in `configure.ac`. But the call to this macro was remove in commit f1f9ee78971b0e560a762a (the last commit that modified `configure.ac`). I make a PR reverting this commit for this file.

**Comment by ClementPernet** [comment]
Fixed by #316
