### ISSUE TITLE
_mm256_permute4x64_pd not found on OSX

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#32]
See 
https://ci.inria.fr/linbox/view/LinBox%20ecosystem/job/FFLAS-FFPACK/Archi=linbox-osx-amd64,Compiler=clang++,SSE=withSSE/16/artifact/config.log

**Comment by romainlebreton** [comment]
Missing test for __FFLASFFPACK_USE_AVX2 (sorry)
Fixed in 8332aecf90daaf384d74f8bfb11e14a91aaa7702
