### ISSUE TITLE
Need help understanding if fflas can perform F_2 matrix multiplication without converting to float

### ISSUE THREAD

**Issue by bjacob** [linbox-team/fflas-ffpack#324]
Hi, I'm looking for the fastest possible linear algebra over F_2, I only need matrix multiplication and LU decomposition.
I'm trying to assess if I should use fflas-ffpack, but looking at source code,
https://github.com/linbox-team/fflas-ffpack/blob/master/fflas-ffpack/fflas/fflas_fgemm.inl ,
it seems to be converting the matrix from F_2 to float?

**Comment by bdsaunders** [comment]
Look to M4RI for fast dense matrix multiply over F2.

**Comment by bjacob** [comment]
Thanks for the quick answer!
