### ISSUE TITLE
Compilation Error using FFLAS-FFPACK

### ISSUE THREAD

**Issue by ZuccaV** [linbox-team/fflas-ffpack#34]
I just installed the fflas-ffpack library, now I would like to use it but I get the following error during the compilation:

In file included from /usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/immintrin.h:41:0,
                 from /usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/x86intrin.h:46,
                 from /usr/include/c++/5.3.1/x86_64-redhat-linux/bits/opt_random.h:33,
                 from /usr/include/c++/5.3.1/random:50,
                 from /usr/include/c++/5.3.1/bits/stl_algo.h:66,
                 from /usr/include/c++/5.3.1/algorithm:62,
                 from /usr/local/include/gmpxx.h:39,
                 from /usr/local/include/gmp++/gmp++.h:33,
                 from main/main.hpp:5,
                 from main/main.cpp:1:
/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/avxintrin.h: Dans la fonction membre statique ‘static Simd256_impl<true, false, true, 4>::vect_t Simd256_impl<true, false, true, 4>::set1(Simd256_impl<true, false, true, 4>::scalar_t)’:
/usr/lib/gcc/x86_64-redhat-linux/5.3.1/include/avxintrin.h:1285:1: erreur : inlining failed in call to always_inline ‘__m256 _mm256_set1_ps(float)’: target specific option mismatch
 _mm256_set1_ps (float __A)
 ^
In file included from /usr/local/soft/fflas-ffpack-2.1/include/fflas-ffpack/fflas/fflas_simd/simd256.inl:35:0,
                 from /usr/local/soft/fflas-ffpack-2.1/include/fflas-ffpack/fflas/fflas_simd.h:208,
                 from /usr/local/soft/fflas-ffpack-2.1/include/fflas-ffpack/fflas/fflas_freduce.h:33,
                 from /usr/local/soft/fflas-ffpack-2.1/include/fflas-ffpack/fflas/fflas.h:99,
                 from /usr/local/soft/fflas-ffpack-2.1/include/fflas-ffpack/fflas-ffpack.h:36,
                 from main/main.hpp:10,
                 from main/main.cpp:1:
/usr/local/soft/fflas-ffpack-2.1/include/fflas-ffpack/fflas/fflas_simd/simd256_float.inl:78:78: erreur : appelé d'ici
     static INLINE CONST vect_t set1(const scalar_t x) { return _mm256_set1_ps(x); }

It seems like it is related to the AVX2 instructions. I joined my config.log file if it can help.

Best,

Vincent
 
[config.log.zip](https://github.com/linbox-team/fflas-ffpack/files/355975/config.log.zip)

**Comment by ClementPernet** [comment]
Hi,

It seems that your call to the compiler did not use the -mavx option.
Could you post the call to the compiler that generated this error?

Note that the proper way to compile a code that uses fflas-ffpack is by getting the CFLAGS from pkgconfig as follows:
`pkgconfig fflas-ffpack --cflags`
This assumes that you have run `make install` beforehand.

**Comment by jgdumas** [comment]
Actually different fflas-ffpack versions clashed.
