### ISSUE TITLE
Tarball for release 2.4.3 does not include all commits of the corresponding tag

### ISSUE THREAD

**Issue by jpoiret** [linbox-team/fflas-ffpack#340]
The tarball leaves out commit f1f9ee78971b0e560a762a5e78d0dc8bc04fa682, which breaks compilation for macaulay2 with GCC 10.

**Comment by jpoiret** [comment]
After looking at this more closely, it seems that tag v2.4.3 was one year after tag 2.4.3, and that the release v2.4.3 on github links to a tarball of 2.4.3.

**Comment by ClementPernet** [comment]
This is very bad indeed.
- tag 2.4.3 was created soon after the release of 2.4.2, probably to declare the next release version. This should not have happened.
-  Indeed upon releasing 2.4.2, the tag v2.4.3 was coined, but the tarballs were generated from the commit of 2.4.3. instead.
As a consequence, there is a discrepancy between the v2.4.3 and the actual tar ball release which was used packaging in various systems.
I can think of only one easy fix which will accommodate with the largely distributed tar balls erroneously based on 2.4.3 and not v2.4.3:
- remove this release entry in github, and create one for fflas-ffpack-2.4.3 at tag 2.4.3 with the same tarballs.
- add a tag v2.4.4 at v2.4.3 and release it as fflas-ffpack-2.4.2
- hopefully this mess will become less problematic, once we release 2.5.0, which we are working on now.

As for f1f9ee7, breaking compilation of macaulay2 with gcc10, I guess it deserves its own issue.

All apologies, as I am very likely the main culprit for this mess.

**Comment by ClementPernet** [comment]
Ok, I just updated the 2.4.3 release to point to the tag 2.4.3 and no longer v2.4.3.
After a second thought, I will not create a 2.4.4 at the position of v2.4.3 to avoid unnecessary complications, since we will release 2.5.0, very  soon.

**Comment by tornaria** [comment]
@ClementPernet: Note also that the `tar.bz2` are named `fflas_ffpack` instead of `fflas-ffpack`. If you will keep doing bz2, maybe you can fix that to be `fflas-ffpack` as well.

**Comment by ClementPernet** [comment]
Well, no, this bz2 archive is produced for integration into sagemath, which requires this naming convention.
