### ISSUE TITLE
ambiguity between _m128 and _m256 back again

### ISSUE THREAD

**Issue by ClementPernet** [linbox-team/fflas-ffpack#358]
https://github.com/linbox-team/fflas-ffpack/runs/4550785824?check_suite_focus=true#step:11:1632

raises an ambiguity between _m128 and _m256 register types
and the compiler suggests that `-fabi-version=6` should fix it.

We already went down this way and #305 removed the use of this option for any gcc>=v5.
Remark that in this log, the compiler is marked as unknown.
(see https://github.com/linbox-team/fflas-ffpack/runs/4550785824?check_suite_focus=true#step:11:1499
I am not sure what's going on here, but the problem appears on many other builds, e.g. https://github.com/linbox-team/fflas-ffpack/runs/4550786736?check_suite_focus=true#step:11:3331

**Comment by cyrilbouvier** [comment]
In this case, https://github.com/linbox-team/fflas-ffpack/runs/4550785824?check_suite_focus=true#step:11:1632, the code runs on Ubuntu Trusty (14.04) which have gcc 4.8 as default compiler (according to https://launchpad.net/ubuntu/trusty/+package/gcc).
gcc < 5 is not supported anymore, the message in configure regarding 'unknown compiler' should be error.

**Comment by ClementPernet** [comment]
Ok, thanks, I thought it was more subtle than that. For the record, I removed debain-jessie, ubuntu-trusty, linuxmint-17 and centos-7 from the list of target systems in 74a8226c.
I guess we still need to have a cleaner behavior when gcc<5 is detected at configure time: exit error instead of printing a message and silently continuing the configuration.
