### ISSUE TITLE
Givaro library could not be used with the compiler

### ISSUE THREAD

**Issue by txgk** [linbox-team/fflas-ffpack#374]
Hi, I'm trying [to package fflas-ffpack to Alpine Linux repository](https://gitlab.alpinelinux.org/alpine/aports/-/merge_requests/39929) and so far l can't get over the configure problem with Givaro - it keeps yielding:
```
configure: error: The Givaro library could not be used with the compiler and the flags set up by the configure script
```
I tried passing different sets of arguments to configure script, disabling Alpine-specific CFLAGS and LDFLAGS, forcing lookup pathes for Givaro, but the error is always the same... You can view log of the build process [here](https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/866509).

**Comment by txgk** [comment]
The way we build Givaro is not fancy at all - it is just `./configure --prefix=/usr --enabled-shared && make && make install`. I don't understand why it could be incompatible...

**Comment by ClementPernet** [comment]
Could you please post the `config.log` file generated by your run of configure in fflas-ffpack ?

**Comment by txgk** [comment]
[This is config.log](https://gist.github.com/txgk/ee21bbea3414b1656514bea429cf8d97) was [generated on x86_64](https://gitlab.alpinelinux.org/grikir02/aports/-/jobs/870609) builder for Alpine Linux.

**Comment by ClementPernet** [comment]
It seems that your installation of gmp does not provide the c++ wrappers `gmpxx.h`.
This is obtained by passing the `--enable-cxx` option to the configure script of gmp. 
So I guess the solution for this issue is in changing the way you build the gmp package for Alpine Linux.

**Comment by ClementPernet** [comment]
For instance, the debian package `libgmp-dev` is compiled with the c++ bindings:
https://packages.debian.org/fr/sid/libgmp-dev

**Comment by txgk** [comment]
Thank you for help! I originally compiled fflas-ffpack without gmp headers (in Alpine gmp is actually compiled with `--enable-cxx`, I just didn't add it), but after I added it to the dependencies, the build got fixed. In that case this message about Givaro is a little misleading since the problem was in the lack of gmp...
