### ISSUE TITLE
test-maxdelayeddim does not compile

### ISSUE THREAD

**Issue by BastienVialla** [linbox-team/fflas-ffpack#39]
Hey, 

test-maxdelayeddim.C does not compile on osx with g++6.
On osx, size_t is a long unsigned int, it cannot be cast to a Givaro::Integer.

[log_test-maxdelayed.txt](https://github.com/linbox-team/fflas-ffpack/files/391003/log_test-maxdelayed.txt)
 @ClementPernet

**Comment by ClementPernet** [comment]
I'm on it

**Comment by ClementPernet** [comment]
fixed
