### ISSUE TITLE
error "NDEBUG and DEBUG both defined"

### ISSUE THREAD

**Issue by jgdumas** [linbox-team/fflas-ffpack#40]
with gmp-6.0.0
---------------
make[3]: Entering directory '/usr/local/soft/linbox/linbox/algorithms'
/bin/sh ../../libtool  --tag=CXX   --mode=compile g++ -DHAVE_CONFIG_H -I. -I../..  -I../../linbox -O2 -Wall -Wextra -Wno-unused-parameter -Wuninitialized -Wconversion -Wcast-qual -pedantic -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wno-long-long -Wno-variadic-macros -Wno-vla -DNDEBUG -UFFLASFFPACK_DEBUG -D__FFLASFFPACK_HAVE_CBLAS -std=gnu++11 -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -fabi-version=6 -fopenmp -std=gnu++11 -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mfpmath=sse -fabi-version=6 -I/usr/local/soft/givaro-3.4/include -I/usr/local/soft/gmp-6/include -I/usr/local/soft/fflas-ffpack-1.4/include -I/usr/local/soft/ntl-6//include     -O0   -Wall -g -DDEBUG -D_LB_DEBUG   -std=gnu++11  -c -o diophantine-solver.lo diophantine-solver.C
libtool: compile:  g++ -DHAVE_CONFIG_H -I. -I../.. -I../../linbox -O2 -Wall -Wextra -Wno-unused-parameter -Wuninitialized -Wconversion -Wcast-qual -pedantic -Wshadow -Wpointer-arith -Wcast-align -Wwrite-strings -Wno-long-long -Wno-variadic-macros -Wno-vla -DNDEBUG -UFFLASFFPACK_DEBUG -D__FFLASFFPACK_HAVE_CBLAS -std=gnu++11 -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -fabi-version=6 -fopenmp -std=gnu++11 -mmmx -mpopcnt -msse -msse2 -msse3 -msse4.1 -msse4.2 -mavx -mfpmath=sse -fabi-version=6 -I/usr/local/soft/givaro-3.4/include -I/usr/local/soft/gmp-6/include -I/usr/local/soft/fflas-ffpack-1.4/include -I/usr/local/soft/ntl-6//include -O0 -Wall -g -DDEBUG -D_LB_DEBUG -std=gnu++11 -c diophantine-solver.C -o diophantine-solver.o
In file included from ../../linbox/integer.h:46:0,
                 from ../../linbox/randiter/abstract.h:31,
                 from ../../linbox/field/abstract.h:33,
                 from ../../linbox/field/archetype.h:51,
                 from ../../linbox/vector/vector-traits.h:57,
                 from ../../linbox/matrix/dense-matrix.h:37,
                 from ../../linbox/algorithms/rational-solver.h:43,
                 from ../../linbox/algorithms/diophantine-solver.h:29,
                 from diophantine-solver.C:26:
/usr/local/soft/givaro-3.4/include/gmp++/gmp++.h:48:2: error: #error "NDEBUG and DEBUG both defined"
 #error "NDEBUG and DEBUG both defined"
  ^

**Comment by romainlebreton** [comment]
@ClementPernet `pkg-config fflas-ffpack --cflags` includes debug flags. So if you compile fflas-ffpack with --enable-debug and linbox without it, you have -DDEBUG defined by fflas-ffpack and -DNDEBUG defined by linbox.
