### ISSUE TITLE
x86_64-specific assembly causes linbox build failure on other arches

### ISSUE THREAD

**Issue by jamesjer** [linbox-team/fflas-ffpack#47]
See https://bugzilla.redhat.com/show_bug.cgi?id=1373305 for the initial report.  The issue is that fflas-ffpack/utils/bit_manipulation.h contains a divide_128 function which is used on all 64-bit architectures, but contains x86_64-specific assembly language.  This causes the linbox build to fail on non-x86_64 64-bit architectures, such as aarch64.

A grep for __asm__ also turned up fflas-ffpack/utils/fflas_memory.h, which invokes the cpuid assembly language instruction.  That should probably also be inside an x86-specific guard.

**Comment by ClementPernet** [comment]
This should be fixed now by dffbaee3107.
