### ISSUE TITLE
TileRecursive more efficient than GaussJordan in parallel

### ISSUE THREAD

**Issue by jgdumas** [linbox-team/fflas-ffpack#54]
with FfpackGaussJordan
> ./benchmark-inverse -p true
Time: 0.261191 Gflops: 61.2577 -q 131071 -n 2000 -i 3 -f "" -t 4 -b 4 -p Y -c N

with FfpackTileRecursive
> ./benchmark-inverse -p true -c Y
Time: 0.194737 Gflops: 82.1622 -q 131071 -n 2000 -i 3 -f "" -t 4 -b 4 -p Y -c Y

**Comment by ClementPernet** [comment]
I will investigate and optimize out Gauss Jordan (the threshold is arbitrarily set to 128 for the moment, which is suboptimal)
What machine is this? 4 cores or 4 hyperhreads?
Did you run it on my latest push of branch parallelInvert ?

**Comment by jgdumas** [comment]
Yes latest push of branch parallelInvert on 4 true cores

**Comment by ClementPernet** [comment]
As a starter: the threshold was 12 and not 128 (`ffpack/ffpack_echelonforms.inl` line 33)
I fixed it and it makes GaussJordan much faster: in sequential: somewhere inbetween SlabRec and TileRec (the fastest).
Then in parallel: GaussJordan becomes the best option:
```
pernet@hpac:~/Logiciels/fflas-ffpack/benchmarks$ /home/gautier/install-3.0.5/bin/komp-run ./benchmark-inverse -p Y  -n 8000
Time: 14.5401 Gflops: 70.4261 -q 131071 -n 8000 -i 3 -f "" -t 32 -b 32 -p Y -c N
pernet@hpac:~/Logiciels/fflas-ffpack/benchmarks$ /home/gautier/install-3.0.5/bin/komp-run ./benchmark-inverse-tr -p Y  -n 8000
Time: 28.2946 Gflops: 36.1906 -q 131071 -n 8000 -i 3 -f "" -t 32 -b 32 -p Y -c N
pernet@hpac:~/Logiciels/fflas-ffpack/benchmarks$ /home/gautier/install-3.0.5/bin/komp-run ./benchmark-inverse-sr -p Y  -n 8000
Time: 52.7066 Gflops: 19.4283 -q 131071 -n 8000 -i 3 -f "" -t 32 -b 32 -p Y -c N
```

**Comment by jgdumas** [comment]
Nope, on my machine behavior is unchanged.

**Comment by ClementPernet** [comment]
Ok, indeed, the same happens on my 4 cores haswell box. Back to work!

**Comment by ClementPernet** [comment]
After #62 GaussJordan now uses PLUQ Tile recursive as a base case and performs faster than the pure PLUQ tile rec version of inverse:

```Slab Rec: 
Time: 1.95863 Gflops: 65.352 -q 131071 -n 4000 -i 3 -f "" -t 4 -b 4 -p Y -c N
Tile Rec: 
Time: 1.05856 Gflops: 120.919 -q 131071 -n 4000 -i 3 -f "" -t 4 -b 4 -p Y -c N
GaussJordan Slab: 
Time: 1.17077 Gflops: 109.33 -q 131071 -n 4000 -i 3 -f "" -t 4 -b 4 -p Y -c N
GaussJordan Tile: 
Time: 0.901317 Gflops: 142.014 -q 131071 -n 4000 -i 3 -f "" -t 4 -b 4 -p Y -c N
```

Issue solved.
