### ISSUE TITLE
Compiling with fflas.h can fail when termios.h is also included

### ISSUE THREAD

**Issue by embray** [linbox-team/fflas-ffpack#57]
This is a fairly unusual corner case, but the standard header termios.h defines a macro called `B0` that conflicts with the variable named `B0` in `fflas/fflas_igemm/igemm_kernels.inl`.  This can happen when compiling any source that happens to include both `fflas.h` and `termios.h` (one such case is described here: https://trac.sagemath.org/ticket/21578).

I would suggest simply renaming the variables.

**Comment by ClementPernet** [comment]
This is terribly annoying that some std package define a macro named B0.
I see no simple way around it else than renaming. This is done in  in 346498a .

**Comment by embray** [comment]
Absolutely agree.  Thanks for the quick fix.
