### ISSUE TITLE
test-frobenius doesn't compile

### ISSUE THREAD

**Issue by bdsaunders** [linbox-team/fflas-ffpack#7]
zebra:~/sandbox/fflas-ffpack/tests> g++ -std=gnu++11    test-frobenius.C   -o test-frobenius -I ../../include
test-frobenius.C:47:49: fatal error: fflas-ffpack/field/modular-positive.h: No such file or directory
 #include "fflas-ffpack/field/modular-positive.h"

Where did modular-positive go?
Is there any other use of CharpolyArithProg in ffpack or linbox?

**Comment by bdsaunders** [comment]
I put in givaro/modular-double instead.  Now get extensive compile time errors.  What is the status of this?   I'd like to have dense matrix Frobenius form working.

**Comment by Breush** [comment]
``modular-positive.h`` has been moved to attic when moving fields to Givaro in ddc9a32fbbfab72c4f0dbfc7b5768a386a4fb1ce.
This file just included a bunch of other files:
```
-#include "fflas-ffpack/field/modular-float.h"
-#include "fflas-ffpack/field/modular-double.h"
-#include "fflas-ffpack/field/modular-int32.h"
-#include "fflas-ffpack/field/modular-uint32.h"
-#include "fflas-ffpack/field/modular-integer.h"
-// #ifdef __x86_64__
-#include "fflas-ffpack/field/modular-int64.h"
-#include "fflas-ffpack/field/modular-uint64.h"
-// #endif
```
One should include ``givaro/modular.h`` instead to get similar effect.

I don't know about the dense matrix Frobenius.

**Comment by bdsaunders** [comment]
After the includes are fixed, the problem is with simd:

g++ -std=gnu++11 test-frobenius.C -o test-frobenius -I../../include
In file included from ../../include/fflas-ffpack/fflas/fflas_simd/simd128.inl:43
:0,
                 from ../../include/fflas-ffpack/fflas/fflas_simd.h:179,
                 from ../../include/fflas-ffpack/fflas/fflas_freduce.h:33,
                 from ../../include/fflas-ffpack/fflas/fflas.h:127,
                 from ../../include/fflas-ffpack/ffpack/ffpack.h:44,
                 from test-frobenius.C:48:
../../include/fflas-ffpack/fflas/fflas_simd/simd128_int64.inl:251:2: warning: #w
arning "The simd greater function is emulate, it may impact the performances." [
-Wcpp]
 #warning "The simd greater function is emulate, it may impact the performances.
"
  ^
../../include/fflas-ffpack/fflas/fflas_simd/simd128_int64.inl:263:2: warning: #w
arning "The simd lesser function is emulate, it may impact the performances." [-
Wcpp]
 #warning "The simd lesser function is emulate, it may impact the performances."
  ^
In file included from ../../include/fflas-ffpack/fflas/fflas_freduce.h:33:0,
                 from ../../include/fflas-ffpack/fflas/fflas.h:127,
                 from ../../include/fflas-ffpack/ffpack/ffpack.h:44,
                 from test-frobenius.C:48:
../../include/fflas-ffpack/fflas/fflas_simd.h:66:49: error: ‘__m128’ does not na
me a type
 std::ostream &operator<<(std::ostream &o, const __m128 &v) {
                                                 ^
../../include/fflas-ffpack/fflas/fflas_simd.h:66:57: error: ISO C++ forbids decl
aration of ‘v’ with no type [-fpermissive]
 std::ostream &operator<<(std::ostream &o, const __m128 &v) {
                                                         ^
../../include/fflas-ffpack/fflas/fflas_simd.h:77:49: error: ‘__m128i’ does not n
ame a type
 std::ostream &operator<<(std::ostream &o, const __m128i &v) {
                                                 ^
../../include/fflas-ffpack/fflas/fflas_simd.h:77:58: error: ISO C++ forbids decl
aration of ‘v’ with no type [-fpermissive]
 std::ostream &operator<<(std::ostream &o, const __m128i &v) {
                                                          ^
../../include/fflas-ffpack/fflas/fflas_simd.h: In function ‘std::ostream& std::o
perator<<(std::ostream&, const int&)’:
../../include/fflas-ffpack/fflas/fflas_simd.h:77:15: error: redefinition of ‘std
::ostream& std::operator<<(std::ostream&, const int&)’
 std::ostream &operator<<(std::ostream &o, const __m128i &v) {
               ^
../../include/fflas-ffpack/fflas/fflas_simd.h:66:15: error: ‘std::ostream& std::
operator<<(std::ostream&, const int&)’ previously defined here
 std::ostream &operator<<(std::ostream &o, const __m128 &v) {
               ^
../../include/fflas-ffpack/fflas/fflas_simd.h: At global scope:
../../include/fflas-ffpack/fflas/fflas_simd.h:86:49: error: ‘__m128d’ does not n
ame a type
 std::ostream &operator<<(std::ostream &o, const __m128d &v) {
                                                 ^
../../include/fflas-ffpack/fflas/fflas_simd.h:86:58: error: ISO C++ forbids decl
aration of ‘v’ with no type [-fpermissive]
 std::ostream &operator<<(std::ostream &o, const __m128d &v) {
                                                          ^
../../include/fflas-ffpack/fflas/fflas_simd.h: In function ‘std::ostream& std::o
perator<<(std::ostream&, const int&)’:
../../include/fflas-ffpack/fflas/fflas_simd.h:86:15: error: redefinition of ‘std
::ostream& std::operator<<(std::ostream&, const int&)’
 std::ostream &operator<<(std::ostream &o, const __m128d &v) {
               ^
../../include/fflas-ffpack/fflas/fflas_simd.h:66:15: error: ‘std::ostream& std::
operator<<(std::ostream&, const int&)’ previously defined here
 std::ostream &operator<<(std::ostream &o, const __m128 &v) {
               ^
../../include/fflas-ffpack/fflas/fflas_simd.h: At global scope:
../../include/fflas-ffpack/fflas/fflas_simd.h:99:49: error: ‘__m256’ does not na
me a type
 std::ostream &operator<<(std::ostream &o, const __m256 &v) {
                                                 ^
../../include/fflas-ffpack/fflas/fflas_simd.h:99:57: error: ISO C++ forbids decl
aration of ‘v’ with no type [-fpermissive]
 std::ostream &operator<<(std::ostream &o, const __m256 &v) {
                                                         ^

**Comment by jgdumas** [comment]
I have added an empty prefetch in case SIMD is not defined.
THis did solve the issue on my architecture and is commited.

**Comment by bdsaunders** [comment]
I'm still getting those simd issues.  Not sure I saw evidence of your commit.

**Comment by jgdumas** [comment]
oups forgot the git push ...

**Comment by bdsaunders** [comment]
Super, thanks.
