### ISSUE TITLE
test-fger fails from time to time

### ISSUE THREAD

**Issue by jgdumas** [linbox-team/fflas-ffpack#9]
Debian 4.2.3-1; g++ 5.2.1
--------
Modular<int64_t, uint64_t> modulo 115352753
q = 115352753 m,n = 46, 8 C := 1.x * y^T + CFAIL
a   :1
m   :46, n   : 8
incx :1, incy : 1, ldC : 8
Error C[0,5]=55152922 D[0,5]=55152923
Error C[0,7]=1029916 D[0,7]=1029917
Error C[5,7]=55894616 D[5,7]=55894615
Error C[15,7]=89883204 D[15,7]=89883203
Error C[17,5]=82652066 D[17,5]=82652067
Error C[17,7]=68451722 D[17,7]=68451721
Error C[19,5]=51301642 D[19,5]=51301641
Error C[19,7]=70554328 D[19,7]=70554329
Error C[20,5]=64629878 D[20,5]=64629877
Error C[20,7]=12279008 D[20,7]=12279011
Error C[24,7]=88267080 D[24,7]=88267081
Error C[25,7]=73418002 D[25,7]=73418004
Error C[30,5]=47031350 D[30,5]=47031349
Error C[30,7]=106218284 D[30,7]=106218281
Error C[33,7]=49970082 D[33,7]=49970081
Error C[34,5]=1700928 D[34,5]=1700929
Error C[34,7]=102680298 D[34,7]=102680297
Error C[36,5]=13240560 D[36,5]=13240561
Error C[36,7]=56790754 D[36,7]=56790755
Error C[37,5]=59959002 D[37,5]=59959003
.....X.X
........
........
........
........
.......X
........
........
........
........
........
........
........
........
........
.......X
........
.....X.X
........
.....X.X
.....X.X
........
........
........
.......X
.......X
........
........
........
........
.....X.X
........
........
.......X
.....X.X
........
.....X.X
.....X.X
.....X.X
........
........
........
........
........
........
........
 -> KO

**Comment by ClementPernet** [comment]
Fixed in 86ec555
